language: node_js
sudo: required # to install newer g++ :(
node_js:
- "4.0.0"
- "0.12"
- "0.11"
- "0.10"
before_install:
- npm install -g npm@'>=2.13.5'
- |
  mkdir -p .npm
  export DISPLAY=:99.0
  sh -e /etc/init.d/xvfb start
script:
- |
  echo "machine github.com login stellar-jenkins password $GITHUB_TOKEN" >~/.netrc
  git config --global user.name "Travis CI"
  git config --global user.email "accounts+github@stellar.org"
  gulp test && gulp build
env:
  global:
    # GITHUB_TOKEN
    - secure: Pc3DwkXywnOGAhUdBZiUCKjyljzrQzPoqm9EEr+UL2BaeaDniFLCLEkuU+ViiuJBo8oPyOIl7I+d86Mi5q06fQx55+xH7DmiW/aj4qKVB2U6Ghn6A3QWkQuvRB1o8SP7iTYRCX480ULZs6AGrMd9y1PFRx/L93fBrO+J/bOtEmg=
    - CXX=g++-4.8 # node bindings in 4.0.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
notifications:
  slack:
    secure: CgXxNEQrQ82EatyF/wSdF0P5rXcWPL+fFZ1lb1aBb8RbVt5gwddJ6xWVD/nYSr6tIJvIYHYhoYsIDPENwezIPsesG7kWXerQhydsEcA34JKxzsStd/TmU6Moxuwy6KTN7yzmL6586nSvoAw9TNPgvRkJFkH07asjGIc9Rlaq7/Y=
deploy:
  - provider: npm
    email: npm@stellar.org
    api_key:
      secure: rQ9OjPbd/6yAgjILpYI4cdrPYPEUvEv/aJF1KrT42KlukLn5jrSGVzuhdVCtv2riNOvxkLFQEzv/Q/DhsB2tJ0nhiad/S21IIaqGmvWZjIUKOHUz91ncEcMDqAMKR1tBGjmtA3J25xbbyPBNFwDRsyNbhjWV2F4iS0Xc9f4abyY=
    skip_cleanup: true
    on:
      tags: true
      repo: stellar/js-stellar-sdk
      node: "0.12" # Deploy only once, no matter which node
  - provider: script
    script: ./bower_publish.sh
    skip_cleanup: true
    on:
      tags: true
      repo: stellar/js-stellar-sdk
      node: "0.12" # Deploy only once, no matter which node
